# Generated by Django 4.0.6 on 2023-06-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DataEntry', '0029_client_activation_request_alter_client_needreview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('addressDetails', models.TextField(blank=True, help_text='العنوان بالتفصيل', max_length=250, null=True)),
                ('notes', models.TextField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_created_by', to='DataEntry.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at_date', models.DateField(auto_now=True, null=True)),
                ('kind', models.CharField(choices=[('C', 'شكوى'), ('S', 'اقتراح'), ('R', 'طلب')], default='OR', max_length=5, null=True)),
                ('body', models.TextField(max_length=500, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestClient', to='cs.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_created_by', to='DataEntry.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        # migrations.CreateModel(
        #     name='Order',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('is_deleted', models.BooleanField(default=False)),
        #         ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
        #         ('created_at_date', models.DateField(auto_now_add=True, null=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True, null=True)),
        #         ('updated_at_date', models.DateField(auto_now=True, null=True)),
        #         ('DueDate', models.DateField(null=True, verbose_name='تاريخ اداء الخدمة')),
        #         ('Status', models.CharField(choices=[('OR', 'تم تلقى الطلب'), ('OIP', 'جارى تنفيذ الطلب'), ('OCD', 'تم تنفيذ الطلب')], default='OR', max_length=5, null=True)),
        #         ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='cs.client')),
        #         ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='cs.service')),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
    ]
