# Generated by Django 4.0.6 on 2023-06-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at_date', models.DateField(auto_now=True, null=True)),
                ('DueDate', models.DateField(null=True, verbose_name='تاريخ اداء الخدمة')),
                ('Status', models.CharField(choices=[('OR', 'تم تلقى الطلب'), ('OIP', 'جارى تنفيذ الطلب'), ('OCD', 'تم تنفيذ الطلب')], default='OR', max_length=5, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='cs.client')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='cs.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
