# Generated by Django 4.0.6 on 2023-05-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0001_initial'),
    ]

    operations = [
    ]
