# Generated by Django 4.0.6 on 2023-04-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
