# Generated by Django 4.0.6 on 2022-09-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_getter', to='DataEntry.employee'),
        ),
    ]
