# Generated by Django 4.0.6 on 2023-05-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0002_auto_20230525_1531'),
    ]

    operations = [
    ]
