# Generated by Django 4.0.6 on 2023-05-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0003_auto_20230525_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activation_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='needReview',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='needReview',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
