# Generated by Django 4.0.6 on 2022-09-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0004_alter_client_addressarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='addressArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='DataEntry.area'),
        ),
    ]
