# Generated by Django 4.0.6 on 2023-04-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0004_alter_service_pricetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='subServices',
        ),
    ]
