# Generated by Django 4.0.6 on 2023-04-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0005_alter_client_addressapartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contractDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
