# Generated by Django 4.0.6 on 2023-04-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0006_client_contractdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='customFilter',
            field=models.CharField(blank=True, help_text='فلتر مخصص', max_length=250, null=True),
        ),
    ]
