# Generated by Django 4.0.6 on 2022-09-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0006_alter_client_addressdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_prev_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_prev_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_prev_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followcontractservices',
            name='created_prev_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
