# Generated by Django 4.0.6 on 2023-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0009_rename_total_amount_followcontractservices_deservedamount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='billSerial',
        ),
        migrations.RemoveField(
            model_name='service',
            name='billed_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='fixedDeliveryDate',
        ),
        migrations.RemoveField(
            model_name='service',
            name='fixedPriceCollectDate',
        ),
        migrations.RemoveField(
            model_name='service',
            name='fixedPriceCollectDate_more',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='priceType',
            field=models.TextField(blank=True, default='شهرى', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='typee',
            field=models.CharField(blank=True, default='شهرى', max_length=50, null=True),
        ),
    ]
