# Generated by Django 4.0.6 on 2022-09-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0009_area_is_deleted_client_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followcontractservices',
            name='collcetStatusNums',
            field=models.IntegerField(blank=True, choices=[('تم الدفع', 'تم الدفع'), ('مطلوب الدفع', 'مطلوب الدفع'), ('فى انتظار ميعاد التحصيل', 'فى انتار ميعاد التحصيل')], db_index=True, default='فى انتظار ميعاد التحصيل', null=True),
        ),
    ]
