# Generated by Django 4.0.6 on 2023-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0010_remove_service_billserial_remove_service_billed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contractDate',
        ),
        migrations.AddField(
            model_name='client',
            name='serviceId',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
