# Generated by Django 4.0.6 on 2022-09-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0011_alter_followcontractservices_collcetstatusnums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followcontractservices',
            name='collcetStatusNums',
            field=models.CharField(blank=True, choices=[('تم الدفع', 'تم الدفع'), ('مطلوب الدفع', 'مطلوب الدفع'), ('فى انتظار ميعاد التحصيل', 'فى انتظار ميعاد التحصيل')], db_index=True, default='فى انتظار ميعاد التحصيل', max_length=50, null=True),
        ),
    ]
