# Generated by Django 4.0.6 on 2023-04-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0011_remove_client_contractdate_client_serviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='followcontractservices',
            name='collectMonth',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='شهر التحصيل'),
        ),
    ]
