# Generated by Django 4.0.6 on 2023-04-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0012_followcontractservices_collectmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='followcontractservices',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='السنة'),
        ),
    ]
