# Generated by Django 4.0.6 on 2022-09-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0014_alter_collectorder_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='billSerial',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='billed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
