# Generated by Django 4.0.6 on 2023-04-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0015_rename_esd_contract_ecd'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='remainAmount',
            field=models.IntegerField(blank=True, null=True, verbose_name='المبلغ المتبقى'),
        ),
    ]
