# Generated by Django 4.0.6 on 2022-10-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0019_contactrequesttypes_offers_simpleservice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='Image',
            new_name='image',
        ),
    ]
