# Generated by Django 4.0.6 on 2023-05-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0020_contract_lastreceiptserial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lastReceiptSerial',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='اخر سريال دفع'),
        ),
    ]
