# Generated by Django 4.0.6 on 2023-05-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0022_followcontractservices_collectrecordserial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payhistory',
            old_name='prevDate',
            new_name='ecd',
        ),
    ]
