# Generated by Django 4.0.6 on 2022-10-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0023_rename_addressarea_client_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nationalId',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='streetName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
