# Generated by Django 4.0.6 on 2022-10-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0024_client_nationalid_client_streetname'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
    ]
