# Generated by Django 4.0.6 on 2022-10-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0029_alter_client_addressdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='source_outside',
            field=models.BooleanField(default=False),
        ),
    ]
