# Generated by Django 4.0.6 on 2022-10-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0029_alter_client_addressdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='providers',
        ),
        migrations.AddField(
            model_name='client',
            name='outsource',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='fixedPriceCollectDate',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
    ]
