# Generated by Django 4.0.6 on 2022-10-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0030_remove_service_providers_client_outsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followcontractservices',
            name='source_outside',
            field=models.BooleanField(default=False),
        ),
    ]
