# Generated by Django 4.0.6 on 2022-10-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0031_followcontractservices_source_outside'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followcontractservices',
            name='source_outside',
        ),
    ]
