# Generated by Django 4.1.2 on 2022-10-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0032_remove_followcontractservices_source_outside'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='missing_info',
            field=models.BooleanField(default=False),
        ),
    ]
