# Generated by Django 4.0.6 on 2022-11-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0035_client_belongs_to_client_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorder',
            name='areas',
            field=models.ManyToManyField(related_name='orders_areas', to='DataEntry.area'),
        ),
    ]
