# Generated by Django 4.0.6 on 2022-11-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0036_collectorder_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorder',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='الشهر'),
        ),
    ]
