# Generated by Django 4.0.6 on 2022-11-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0040_client_deserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='deserved',
            field=models.IntegerField(default=0, help_text='لجمالى المستحق على العميل'),
        ),
    ]
