# Generated by Django 4.0.6 on 2022-11-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0041_alter_client_deserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collectorder',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactrequesttypes',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='followcontractservices',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requestsimpleservice',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simpleservice',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='collectorder',
            name='areas',
            field=models.ManyToManyField(related_name='orders_areas', to='DataEntry.area', verbose_name='المناطق'),
        ),
        migrations.AlterField(
            model_name='collectorder',
            name='clients',
            field=models.ManyToManyField(related_name='orders_clients', to='DataEntry.client', verbose_name='العملاء'),
        ),
    ]
