# Generated by Django 4.0.6 on 2022-12-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0042_area_is_test_collectorder_is_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
