# Generated by Django 4.0.6 on 2022-12-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0043_alter_contract_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='followcontractservices',
            name='area',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
