# Generated by Django 4.0.6 on 2022-12-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0044_followcontractservices_area_alter_client_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الايميل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كلمة السر'),
        ),
    ]
