# Generated by Django 4.0.6 on 2023-01-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0047_typee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
