# Generated by Django 4.0.6 on 2023-01-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0048_employee_job2_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job2',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
