# Generated by Django 4.0.6 on 2023-04-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0002_alter_service_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='followcontractservices',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
