# Generated by Django 4.0.6 on 2023-04-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0003_followcontractservices_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='priceType',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
