# Generated by Django 4.0.6 on 2023-04-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0005_remove_contract_subservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followcontractservices',
            name='subService',
        ),
    ]
