# Generated by Django 4.0.6 on 2023-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activation_request',
            field=models.BooleanField(default=False),
        ),
    ]
