# Generated by Django 4.0.6 on 2023-09-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='service',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
