# Generated by Django 4.0.6 on 2022-09-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0002_contract_belong_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
