# Generated by Django 4.0.6 on 2023-05-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0002_client_activation_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='needReview',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='needReview',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
