# Generated by Django 4.2.3 on 2023-09-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0002_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='depart',
            field=models.CharField(blank=True, default='ادخال البيانات', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
