# Generated by Django 4.0.6 on 2023-05-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0004_followcontractservices_remainamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='remainAmount',
            field=models.IntegerField(blank=True, null=True, verbose_name='المبلغ المتبقى'),
        ),
    ]
