# Generated by Django 4.0.6 on 2023-04-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0004_alter_client_addressbuilding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='addressApartment',
            field=models.CharField(blank=True, help_text='تفاصيل الشقه', max_length=150, null=True),
        ),
    ]
