# Generated by Django 4.0.6 on 2022-09-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0005_alter_client_addressarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='addressDetails',
            field=models.TextField(blank=True, help_text='اى تفاصيل إخرى للعنوان', max_length=50, null=True),
        ),
    ]
