# Generated by Django 4.0.6 on 2023-04-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0008_contract_lastpay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followcontractservices',
            old_name='total_amount',
            new_name='deservedAmount',
        ),
        migrations.RenameField(
            model_name='followcontractservices',
            old_name='remain_amount',
            new_name='remainAmount',
        ),
        migrations.RemoveField(
            model_name='followcontractservices',
            name='area',
        ),
        migrations.RemoveField(
            model_name='followcontractservices',
            name='collcetStatusNums',
        ),
        migrations.RemoveField(
            model_name='followcontractservices',
            name='collected_amount',
        ),
        migrations.RemoveField(
            model_name='followcontractservices',
            name='collected_date',
        ),
        migrations.RemoveField(
            model_name='followcontractservices',
            name='collected_month',
        ),
        migrations.RemoveField(
            model_name='followcontractservices',
            name='created_prev_date',
        ),
        migrations.RemoveField(
            model_name='followcontractservices',
            name='serviceCollectDayEnd',
        ),
        migrations.RemoveField(
            model_name='followcontractservices',
            name='serviceCollectDayStart',
        ),
        migrations.RemoveField(
            model_name='followcontractservices',
            name='serviceDueDate',
        ),
        migrations.RemoveField(
            model_name='followcontractservices',
            name='serviceDueStatus',
        ),
        migrations.RemoveField(
            model_name='followcontractservices',
            name='startingDate',
        ),
        migrations.AddField(
            model_name='followcontractservices',
            name='collcetStatus',
            field=models.CharField(blank=True, choices=[('wecd', 'فى انتظار ميعاد التحصيل'), ('pr', 'مطلوب الدفع'), ('pip', 'جارى الدفع'), ('pd', 'تم الدفع'), ('lp', 'متأخر الدفع')], default='wecd', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='followcontractservices',
            name='collectedAmount',
            field=models.IntegerField(blank=True, null=True, verbose_name='المبلغ الذى تم تحصيله'),
        ),
        migrations.AddField(
            model_name='followcontractservices',
            name='collectedDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التحصيل الفعلى'),
        ),
        migrations.AddField(
            model_name='followcontractservices',
            name='ecd',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ  التحصيل المفترض'),
        ),
        migrations.CreateModel(
            name='PayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at_date', models.DateField(auto_now=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الشهر')),
                ('CollectOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataEntry.collectorder')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_pay_history', to='DataEntry.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
