# Generated by Django 4.0.6 on 2022-09-28 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0012_alter_followcontractservices_collcetstatusnums'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at_date', models.DateField(auto_now=True, null=True)),
                ('required', models.IntegerField(blank=True, null=True, verbose_name='المبلغ المطلوب تحصيله')),
                ('clients', models.ManyToManyField(blank=True, null=True, related_name='clients', to='DataEntry.client')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='DataEntry.employee', verbose_name='المحصل')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
