# Generated by Django 4.0.6 on 2023-04-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0013_followcontractservices_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='esd',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع المفترض'),
        ),
    ]
