# Generated by Django 4.0.6 on 2022-09-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0016_alter_collectorder_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followcontractservices',
            name='collected_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
