# Generated by Django 4.0.6 on 2023-04-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0016_contract_remainamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='receiptNum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الايصال'),
        ),
    ]
