# Generated by Django 4.0.6 on 2022-09-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0017_followcontractservices_collected_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='followcontractservices',
            name='collected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followcontractservices',
            name='collected_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الشهر'),
        ),
    ]
