# Generated by Django 4.0.6 on 2023-05-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0018_collectrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='followcontractservices',
            name='collectedConfirmDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ تأكيد التحصيل الفعلى'),
        ),
    ]
