# Generated by Django 4.0.6 on 2022-10-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0021_client_activation_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
