# Generated by Django 4.0.6 on 2023-05-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0024_collectionrecord_remove_collectrecord_receiptnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrecord',
            name='receiptNum',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='عدد الايصالات'),
        ),
    ]
