# Generated by Django 4.0.6 on 2023-05-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0026_alter_client_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='activation_request',
            new_name='needReview',
        ),
    ]
