# Generated by Django 4.0.6 on 2023-05-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0027_rename_activation_request_client_needreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='needReview',
            field=models.BooleanField(default=False),
        ),
    ]
