# Generated by Django 4.0.6 on 2022-10-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0027_client_contactme'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default='user_profile_image_placeholer.png', upload_to='images/clients/'),
        ),
    ]
