# Generated by Django 4.0.6 on 2023-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0028_contract_needreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activation_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='needReview',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='needReview',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
