# Generated by Django 4.0.6 on 2023-09-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0031_remove_contract_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='services',
            field=models.ManyToManyField(related_name='services', to='DataEntry.service'),
        ),
    ]
