# Generated by Django 4.0.6 on 2023-09-16 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0032_contract_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='services',
        ),
    ]
