# Generated by Django 4.0.6 on 2023-09-16 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0033_remove_contract_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_client', to='DataEntry.service'),
        ),
    ]
