# Generated by Django 4.0.6 on 2023-09-18 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0034_alter_contract_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='services',
            field=models.ManyToManyField(related_name='services', to='DataEntry.service'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_client', to='DataEntry.service'),
        ),
    ]
