# Generated by Django 4.0.6 on 2023-09-18 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0035_contract_services_alter_contract_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='services',
        ),
        migrations.AddField(
            model_name='contract',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicess', to='DataEntry.service'),
        ),
    ]
