# Generated by Django 4.0.6 on 2023-09-18 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0036_remove_contract_services_contract_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='DataEntry.service'),
        ),
    ]
