# Generated by Django 4.2.3 on 2023-09-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0038_alter_contract_service_remove_contract_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='collectDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
