# Generated by Django 4.2.3 on 2023-09-21 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0040_remove_contract_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataEntry.service'),
        ),
    ]
