# Generated by Django 4.2.3 on 2023-09-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntry', '0041_alter_contract_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='service',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
